version: '3.8'

services:
  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - spring-redis-net

volumes:
  redis-data:

networks:
  spring-redis-net:
    driver: bridge